services:
  - type: web
    name: propfirms
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production 