services:
  - type: web
    name: propfirms
    env: static
    buildCommand: npm run build
    staticPublishPath: ./out
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production 